// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

namespace AWS.AgentCore.Testing.Models;

/// <summary>
/// Represents a single message in a chat conversation between a user and the agent.
/// </summary>
public class ChatMessage
{
    /// <summary>
    /// Unique identifier for this message.
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// The role of the message sender (User or Assistant).
    /// </summary>
    public ChatRole Role { get; set; }

    /// <summary>
    /// The text content of the message. For assistant messages, may contain Markdown.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// The UTC timestamp when this message was created.
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// The role of a chat message sender.
/// </summary>
public enum ChatRole
{
    /// <summary>
    /// A message sent by the user.
    /// </summary>
    User,

    /// <summary>
    /// A response generated by the agent.
    /// </summary>
    Assistant
}
