<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\public.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.BedrockAgentCore" Version="4.0.20.1" />
        <PackageReference Include="AWSSDK.CloudFormation" Version="4.0.8.21" />
        <PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.9" />
        <PackageReference Include="AWSSDK.ECR" Version="4.0.13.3" />
        <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.6.6" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Infrastructure/inttest-stack.template.json" />
        <EmbeddedResource Include="Infrastructure/inttest-runtimes.template.json" />
    </ItemGroup>

</Project>
