version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 10.x

  build:
    commands:
      - dotnet build AWS.AgentCore.slnx -c Release
      - dotnet test AWS.AgentCore.slnx -c Release --no-build --logger trx --results-directory ./testresults
reports:
    aws-dotnet-ai-tests:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'