<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="13.3.3" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.3.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AWS.AgentCore.Testing\AWS.AgentCore.Testing.csproj" IsAspireProjectResource="false" />
        <ProjectReference Include="..\AnnotationsSample\AnnotationsSample.csproj" />
        <ProjectReference Include="..\AnnotationsStreamingAgent\AnnotationsStreamingAgent.csproj" />
        <ProjectReference Include="..\ChatBotUI\ChatBotUI.csproj" />
        <ProjectReference Include="..\MicrosoftAgentFrameworkSample\MicrosoftAgentFrameworkSample.csproj" />
        <ProjectReference Include="..\NativeAotAnnotations\NativeAotAnnotations.csproj" />
        <ProjectReference Include="..\NativeAotExtensions\NativeAotExtensions.csproj" />
        <ProjectReference Include="..\RemoteMcpAgent\RemoteMcpAgent.csproj" />
        <ProjectReference Include="..\StreamingAgent\StreamingAgent.csproj" />
    </ItemGroup>

</Project>
