// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using AWS.AgentCore.Hosting;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.DependencyInjection;
using Moq;

namespace AWS.AgentCore.Hosting.UnitTests;

public class AgentCoreRuntimeContextTests : IAsyncDisposable
{
    private WebApplication? _app;

    [Fact]
    public async Task SessionId_ExtractedFromHeader()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("X-Amzn-Bedrock-AgentCore-Runtime-Session-Id", "sess-abc");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("sess-abc", captured.SessionId);
    }

    [Fact]
    public async Task SessionId_NullWhenHeaderMissing()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        await client.PostAsJsonAsync("/invocations", new TestRequest("test"), ct);

        Assert.NotNull(captured);
        Assert.Null(captured.SessionId);
    }

    [Fact]
    public async Task RequestId_ExtractedFromAgentCoreHeader()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("X-Amzn-Bedrock-AgentCore-Runtime-Request-Id", "req-from-header");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("req-from-header", captured.RequestId);
    }

    [Fact]
    public async Task RequestId_FallsBackToAmznRequestId()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("x-amzn-requestid", "req-from-amzn");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("req-from-amzn", captured.RequestId);
    }

    [Fact]
    public async Task RequestId_AutoGeneratedWhenNoHeaders()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        await client.PostAsJsonAsync("/invocations", new TestRequest("test"), ct);

        Assert.NotNull(captured);
        Assert.NotNull(captured.RequestId);
        Assert.NotEmpty(captured.RequestId);
        Assert.True(Guid.TryParse(captured.RequestId, out _), "Auto-generated RequestId should be a valid GUID");
    }

    [Fact]
    public async Task RequestId_PrefersAgentCoreHeaderOverAmznRequestId()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("X-Amzn-Bedrock-AgentCore-Runtime-Request-Id", "primary");
        httpRequest.Headers.Add("x-amzn-requestid", "fallback");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("primary", captured.RequestId);
    }

    [Fact]
    public async Task AccessToken_ExtractedFromHeader()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("WorkloadAccessToken", "token-xyz");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("token-xyz", captured.AccessToken);
    }

    [Fact]
    public async Task OAuth2CallbackUrl_ExtractedFromHeader()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("OAuth2CallbackUrl", "https://example.com/callback");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("https://example.com/callback", captured.OAuth2CallbackUrl);
    }

    [Fact]
    public async Task Authorization_ExtractedFromHeader()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("Authorization", "Bearer jwt-token-123");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal("Bearer jwt-token-123", captured.Authorization);
    }

    [Fact]
    public async Task CustomHeaders_ExtractedWithPrefixStripped()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("X-Amzn-Bedrock-AgentCore-Runtime-Custom-TenantId", "acme");
        httpRequest.Headers.Add("X-Amzn-Bedrock-AgentCore-Runtime-Custom-UserId", "user-42");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Equal(2, captured.CustomHeaders.Count);
        Assert.Equal("acme", captured.CustomHeaders["TenantId"]);
        Assert.Equal("user-42", captured.CustomHeaders["UserId"]);
    }

    [Fact]
    public async Task CustomHeaders_EmptyWhenNonePresent()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        await client.PostAsJsonAsync("/invocations", new TestRequest("test"), ct);

        Assert.NotNull(captured);
        Assert.Empty(captured.CustomHeaders);
    }

    [Fact]
    public async Task CustomHeaders_CaseInsensitivePrefix()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("x-amzn-bedrock-agentcore-runtime-custom-mykey", "lowercase-value");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.Single(captured.CustomHeaders);
        Assert.Equal("lowercase-value", captured.CustomHeaders["mykey"]);
    }

    [Fact]
    public async Task AllHeaders_ContainsAllRequestHeaders()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        var httpRequest = CreateInvocationRequest(new TestRequest("test"));
        httpRequest.Headers.Add("X-Amzn-Bedrock-AgentCore-Runtime-Session-Id", "sess-123");
        httpRequest.Headers.Add("X-Custom-Unrelated", "some-value");

        await client.SendAsync(httpRequest, ct);

        Assert.NotNull(captured);
        Assert.True(captured.AllHeaders.ContainsKey("X-Amzn-Bedrock-AgentCore-Runtime-Session-Id"));
        Assert.True(captured.AllHeaders.ContainsKey("X-Custom-Unrelated"));
        Assert.True(captured.AllHeaders.ContainsKey("Content-Type")); // set by JsonContent
    }

    [Fact]
    public async Task AllHeaders_NullPropertiesWhenHeadersMissing()
    {
        var ct = TestContext.Current.CancellationToken;
        AgentCoreRuntimeContext? captured = null;

        var (_, client) = await CreateTestAppAsync(
            async (TestRequest request, AgentCoreRuntimeContext context) =>
            {
                captured = context;
                return "ok";
            });

        await client.PostAsJsonAsync("/invocations", new TestRequest("test"), ct);

        Assert.NotNull(captured);
        Assert.Null(captured.SessionId);
        Assert.Null(captured.AccessToken);
        Assert.Null(captured.OAuth2CallbackUrl);
        Assert.Null(captured.Authorization);
    }

    private static HttpRequestMessage CreateInvocationRequest(TestRequest body)
    {
        var request = new HttpRequestMessage(HttpMethod.Post, "/invocations");
        request.Content = JsonContent.Create(body);
        return request;
    }

    private async Task<(WebApplication app, HttpClient client)> CreateTestAppAsync(Delegate handler)
    {
        var builder = WebApplication.CreateBuilder();
        builder.WebHost.UseUrls("http://127.0.0.1:0");

        var mockChatClient = new Mock<IChatClient>();
        builder.Services.AddSingleton(mockChatClient.Object);
        builder.Services.AddLogging();

        _app = builder.Build();

        _app.MapAgentCore<TestRequest>(handler);

        await _app.StartAsync();

        var client = new HttpClient
        {
            BaseAddress = new Uri(_app.Urls.First())
        };

        return (_app, client);
    }

    public async ValueTask DisposeAsync()
    {
        if (_app is not null)
            await _app.DisposeAsync();
    }
}
