// <auto-generated/>
// Generated by AWS.AgentCore.SourceGenerator

using AWS.AgentCore;
using AWS.AgentCore.Extensions;
using Microsoft.Extensions.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddTransient<MyAgent>();

var app = builder.Build();

app.MapAgentCore<PromptRequest>(
    handler: (PromptRequest request) =>
    {
        var agent = app.Services.GetRequiredService<MyAgent>();
        return agent.Handle(request);
    }
);

app.Run();
