// <auto-generated/>
// Generated by AWS.AgentCore.SourceGenerator

using AWS.AgentCore;
using AWS.AgentCore.Extensions;
using Microsoft.Extensions.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddTransient<TestApp.MyAgent>();

var app = builder.Build();

app.MapAgentCore<TestApp.MyRequest>(
    handler: (TestApp.MyRequest request) =>
    {
        var agent = app.Services.GetRequiredService<TestApp.MyAgent>();
        return agent.Handle(request);
    }
);

app.Run();
