// <auto-generated/>
// Generated by AWS.AgentCore.SourceGenerator
#nullable enable

using AWS.AgentCore.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddTransient<TestApp.MyAgent>();

var app = builder.Build();

app.MapAgentCore<TestApp.MyRequest>(
    async (request, context, services, ct) =>
    {
        var agent = services.GetRequiredService<TestApp.MyAgent>();
        return await agent.Handle(request);
    }
);

app.Run();
