// <auto-generated/>
// Generated by AWS.AgentCore.SourceGenerator

using AWS.AgentCore;
using AWS.AgentCore.Extensions;
using Microsoft.Extensions.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);

var startup = new TestApp.Startup();
startup.ConfigureServices(builder);

builder.Services.AddTransient<TestApp.MyAgent>();

var app = builder.Build();

app.MapAgentCore<TestApp.PromptRequest>(
    async (request, context, services, ct) =>
    {
        var agent = services.GetRequiredService<TestApp.MyAgent>();
        return await agent.Handle(request, context, ct);
    }
);

app.Run();
