// <auto-generated/>
// Generated by AWS.AgentCore.SourceGenerator

using AWS.AgentCore;
using AWS.AgentCore.Extensions;
using Microsoft.Extensions.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);

var startup = new TestApp.Startup();
startup.ConfigureServices(builder);

builder.Services.AddTransient<TestApp.MyAgent>();

var app = builder.Build();

app.MapAgentCore<TestApp.PromptRequest>(
    handler: (TestApp.PromptRequest request, AWS.AgentCore.AgentCoreRuntimeContext context, System.Threading.CancellationToken ct) =>
    {
        var agent = app.Services.GetRequiredService<TestApp.MyAgent>();
        return agent.Handle(request, context, ct);
    }
);

app.Run();
