// <auto-generated/>
// Generated by AWS.AgentCore.SourceGenerator

using AWS.AgentCore;
using AWS.AgentCore.Extensions;
using Microsoft.Extensions.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddTransient<TestApp.MyAgent>();

var app = builder.Build();

app.MapAgentCore<TestApp.PromptRequest>(
    async (request, context, services, ct) =>
    {
        var agent = services.GetRequiredService<TestApp.MyAgent>();
        return await agent.Handle(request, ct);
    }
    , pingHandler: async (services, ct) =>
    {
        var agent = services.GetRequiredService<TestApp.MyAgent>();
        await System.Threading.Tasks.Task.CompletedTask;
        agent.Ping();
    }
);

app.Run();
